### ISSUE TITLE
Errors in some kanji

### ISSUE THREAD

**Issue by emi300** [googlefonts/zen-marugothic#4]
I found errors in the following Kanji characters. All of them seem to be missing one stroke. Thank you.

1. 求 (The seventh stroke is missing)

2. 堵屠箸賭薯儲藷瀦 (⭕者 ❌者)
![Screenshot_20230126-150521~2](https://user-images.githubusercontent.com/75617350/214768980-38ef59bb-d77b-4d4d-b3a7-ed739d529588.png)

**Comment by davelab6** [comment]
This was fixed in decae11
